[package]
name = "KrakenMultisig"
edition = "2024.alpha"
license = "MIT" 
authors = ["Thouny (thouny@tuta.io)", "Jose (jose@interestprotocol.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet", override = true }
KrakenExtensions = { local = "../extensions" }

[addresses]
kraken_multisig = "0x4708153b0fb608912ee529addf987d17c1b9a60339d1844cb2a6680b19759ff0"
kraken_extensions = "0xe756e0a7e94636cef926f3433a606f18bec42664d257ba4ea76593a5558aa47d"