[package]
name = "KrakenMultisig"
edition = "2024.alpha"
license = "MIT"
authors = [
  "Thouny (thouny@tuta.io)",
  "Jose (jose@interestprotocol.com)"
]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"

[dependencies.KrakenExtensions]
local = "../extensions"

[dev-dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "testnet"

[dev-dependencies.KrakenExtensions]
local = "../extensions"

[addresses]
kraken_multisig = "_"
kraken_extensions = "_"

[dev-addresses]
kraken_multisig = "0xb1e5559c3a13e645f822992a870c21a068f5e2e6fa94fa30da41677e4249097c"
kraken_extensions = "0x6a044e64112bd8ccfbe05b6efdf5cb187751b2637cd5b2eb46fee5da83b851be"
