[package]
name = "account_protocol"
edition = "2024.beta"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.account_extensions]
local = "../extensions"

[addresses]
account_protocol = "0xcababb3174ca41c616a691024e98e37379e15af969e56b5992fa8139c354c6f5"
account_extensions = "0x162a649c6b0edc3bd1385124afdeffd6f85ab578484dad15c82326438219a347"
