[package]
name = "AccountActions"
edition = "2024.beta"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.Kiosk]
git = "https://github.com/thounyy/apps.git"
subdir = "kiosk"
rev = "testnet"

[dependencies.AccountProtocol]
local = "../protocol"

[dependencies.AccountExtensions]
local = "../extensions"

[addresses]
account_actions = "0xf477dbfad6ab1de1fdcb6042c0afeda2aa5bf12eb7ef42d280059fc8d6c36c94"
account_protocol = "0x10c87c29ea5d5674458652ababa246742a763f9deafed11608b7f0baea296484"
account_extensions = "0x87bee60d3ea6dc5b42e1074134373af27733fb3c5ebc3ac8e013901426d85d53"
kiosk = "0xbd8fc1947cf119350184107a3087e2dc27efefa0dd82e25a1f699069fe81a585"
