[package]
name = "account_actions"
edition = "2024.beta"
license = "Apache-2.0"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.Kiosk]
git = "https://github.com/thounyy/apps.git"
subdir = "kiosk"
rev = "testnet"

[dependencies.AccountProtocol]
local = "../protocol"

[dependencies.AccountExtensions]
local = "../extensions"

[addresses]
account_actions = "0x14ad3f7d7169562b9fa761288f9c0f0bcbb745f51de71ad06dd791ca44a2ee98"
account_protocol = "0xdbf6eb7acfe83ce0f26fd884ea77b1358395e85dac4c47effd4c50be4d810afc"
account_extensions = "0x1ac1e0ddfc88c189c78a6001a77c80f36a820335448bc110f2885f809e91cb62"
kiosk = "0xbd8fc1947cf119350184107a3087e2dc27efefa0dd82e25a1f699069fe81a585"
