[package]
name = "AccountActions"
edition = "2024.beta"
license = "MIT"
authors = [ "Thouny (thouny@tuta.io)" ]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.Kiosk]
git = "https://github.com/thounyy/apps.git"
subdir = "kiosk"
rev = "testnet"

[dependencies.AccountProtocol]
local = "../protocol"

[dependencies.AccountConfig]
local = "../config"

[dependencies.AccountExtensions]
local = "../extensions"

[addresses]
account_config = "0x15e11747882913076d286d9ed9a34f667ce45c69cbd5ac2d6fb2a265d0ce38f6"
account_actions = "0x5157065814a71c09b3d91ab2770115b0c6ee429b4282aa83abd1bfc809ea6e1c"
account_protocol = "0x209df05fc0453a320ab36923e62f25dde5648974edb3460620d76142dd1e2b07"
account_extensions = "0x37ba6b53612b2641aee61dd82d4fd8c0464dacc2a4427c3792603d6c1f8db221"
kiosk = "0xbd8fc1947cf119350184107a3087e2dc27efefa0dd82e25a1f699069fe81a585"
