[package]
name = "KrakenExtensions"
edition = "2024.alpha"
license = "MIT"
authors = [
  "Thouny (thouny@tuta.io)",
  "Jose (jose@interestprotocol.com)"
]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"

[dev-dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "testnet"

[addresses]
kraken_extensions = "_"

[dev-addresses]
kraken_extensions = "0x2d1f315f2b4f5cb64901b054c7f315a03f0aea3f49f6e6c9b74cbd1d12f4b6c7"
