[package]
name = "Kraken"
edition = "2024.beta"
license = "MIT" 
authors = ["Thouny (thouny@tuta.io)", "Jose (jose@interestprotocol.com)"]

[dependencies]
Sui = { override = true, git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
Kiosk = { git = "https://github.com/MystenLabs/apps.git", subdir = "kiosk", rev = "testnet" }
# Kiosk = { local = "../../kraken-sdk/test/packages/kiosk" } # for tests on localnet

[addresses]
kraken = "0x0"

