[package]
name = "Kraken"
edition = "2024.beta"
license = "MIT" 
authors = ["Thouny (thouny@tuta.io)", "Jose (jose@interestprotocol.com)"]

[dependencies]
Sui = { override = true, git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
Kiosk = { git = "https://github.com/MystenLabs/apps.git", subdir = "kiosk", rev = "testnet" }

# [dev-dependencies]
# Kiosk = { git = "https://github.com/MystenLabs/apps.git", subdir = "kiosk", rev = "main" }
# Kiosk = { local = "../../kraken-sdk/test/packages/kiosk" } # for tests on localnet

[addresses]
kraken = "0x0"
kiosk = "0xbd8fc1947cf119350184107a3087e2dc27efefa0dd82e25a1f699069fe81a585"
std = "0x1"
sui = "0x2"

# [dev-addresses]
# kiosk = "0x434b5bd8f6a7b05fede0ff46c6e511d71ea326ed38056e3bcd681d2d7c2a7879"